# Loadtest Dockerfile
# Used for running load tests against the rate limiting server

FROM node:22-slim

WORKDIR /app


COPY package*.json ./

RUN npm install


COPY . .


RUN npm run build


CMD ["npm", "run", "loadtest"]
