services:
  redis:
    image: redis:7
    container_name: benchmark-redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no --maxmemory 1gb --maxmemory-policy volatile-lru
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    cap_add:
      - SYS_RESOURCE
    networks:
      - benchmark_network

  valkey:
    image: valkey/valkey:8.1
    container_name: benchmark-valkey
    ports:
      - "8080:6379"
    command: valkey-server --save "" --appendonly no --maxmemory 1gb --maxmemory-policy volatile-lru
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    cap_add:
      - SYS_RESOURCE
    networks:
      - benchmark_network

networks:
  benchmark_network:
    driver: bridge
