global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['host.docker.internal:9464']
        labels:
          service: 'rate-limiter-benchmark'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  - job_name: 'valkey'
    static_configs:
      - targets: ['valkey-exporter:9121']
        labels:
          service: 'valkey'
